'use client';
import {useState} from 'react';
import {Drawer} from '@/components/smart/Drawer';
import {ActionForm} from '@/components/ui/ActionForm';
import {createWorkOrder} from '@/lib/work-orders/actions';
import {useCommandCopy} from '@/components/ui/LocaleProvider';
import {workspaceCopy} from '@/lib/i18n/workspace-copy';
import {inputClass} from '@/components/ui/primitives';
export function CreateWorkOrderFlow({customers,vessels,initialCustomer=''}:{customers:{id:string;first_name:string;last_name:string}[];vessels:{id:string;name:string|null;current_customer_id:string|null}[];initialCustomer?:string}){
 const {locale}=useCommandCopy();const t=workspaceCopy[locale];const [step,setStep]=useState(0);const [customer,setCustomer]=useState(initialCustomer);const [vessel,setVessel]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [priority,setPriority]=useState('normal');
 return <Drawer label={t.newOrder} title={t.newOrder}><ActionForm action={createWorkOrder}><input type="hidden" name="customerId" value={customer}/><input type="hidden" name="vesselId" value={vessel}/><input type="hidden" name="title" value={title}/><input type="hidden" name="description" value={description}/><input type="hidden" name="priority" value={priority}/><p className="kcc-step">0{step+1} / 03 · {[t.identity,t.service,t.review][step]}</p><div className="h-1 bg-white/10 rounded-full mb-6"><div style={{width:`${(step+1)/3*100}%`}} className="h-full bg-sky-400 transition-all rounded-full"/></div>{step===0?<div className="space-y-5"><label className="block">{t.customer}<select className={inputClass} value={customer} onChange={e=>{setCustomer(e.target.value);setVessel('');}}><option value="">{t.select}</option>{customers.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><label className="block">{t.vessel}<select className={inputClass} disabled={!customer} value={vessel} onChange={e=>setVessel(e.target.value)}><option value="">{t.select}</option>{vessels.filter(v=>v.current_customer_id===customer).map(v=><option key={v.id} value={v.id}>{v.name||v.id}</option>)}</select></label></div>:step===1?<div className="space-y-5"><label className="block">{t.title}<input className={inputClass} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">{t.description}<textarea rows={4} className={inputClass} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="block">{t.priority}<select className={inputClass} value={priority} onChange={e=>setPriority(e.target.value)}>{(['low','normal','high','urgent'] as const).map(p=><option key={p} value={p}>{t[p]}</option>)}</select></label></div>:<section className="kcc-mission space-y-3"><p className="kcc-eyebrow">{customers.find(c=>c.id===customer)?.first_name} · {vessels.find(v=>v.id===vessel)?.name}</p><h3 className="text-2xl font-semibold">{title}</h3><p className="text-cool-gray whitespace-pre-wrap">{description}</p><p>{t.priority}: {t[priority as 'normal']}</p></section>}<div className="kcc-actions mt-8">{step>0&&<button type="button" className="kcc-action" onClick={()=>setStep(step-1)}>{t.back}</button>}{step<2?<button type="button" className="kcc-action" disabled={step===0?(!customer||!vessel):!title.trim()} onClick={()=>setStep(step+1)}>{t.next} →</button>:<button type="submit" className="kcc-action">{t.create} →</button>}</div></ActionForm></Drawer>;
}
