import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {getSessionContext} from '@/lib/auth/session';
import {getActiveOrganizationId} from '@/lib/auth/active-org';
import {getLocale} from '@/lib/i18n/server';
import {ActionForm} from '@/components/ui/ActionForm';
import {recordExpense} from '@/lib/finances/actions';
import {Field,inputClass} from '@/components/ui/primitives';
export default async function FinancesPage({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const session=await getSessionContext();const org=await getActiveOrganizationId(session.memberships);const role=session.memberships.find(m=>m.organization_id===org)?.role;if(!session.isKccAdmin&&!['company_owner','company_admin'].includes(role??''))redirect('/dashboard');
 const locale=await getLocale();const es=locale==='es';const params=await searchParams;const now=new Date().toISOString().slice(0,10);const valid=(d:string|undefined)=>!!d&&/^\d{4}-\d{2}-\d{2}$/.test(d);
 const from=valid(params.from)?params.from!:now.slice(0,7)+'-01';const to=valid(params.to)?params.to!:now;const db=await createClient();
 const [{data:summary,error},{data:expenses,error:expenseError}]=await Promise.all([db.rpc('get_company_cash_summary',{p_org:org,p_from:from,p_to:to}),db.from('company_expenses').select('*').eq('organization_id',org).gte('paid_on',from).lte('paid_on',to).order('paid_on',{ascending:false}).limit(100)]);
 return <div className="max-w-6xl space-y-6"><header className="flex justify-between gap-4"><h1 className="text-3xl font-semibold">{es?'Finanzas y equipo':'Finances & team'}</h1><Link href="/team" className="text-gold">{es?'Remuneración →':'Compensation →'}</Link></header>
 <form className="flex flex-wrap gap-3 items-end"><label>{es?'Desde':'From'}<input name="from" type="date" defaultValue={from} className={inputClass}/></label><label>{es?'Hasta':'To'}<input name="to" type="date" defaultValue={to} className={inputClass}/></label><button className="command-action">{es?'Actualizar':'Update'}</button></form>
 {error?<p role="alert" className="text-amber-200">{es?'No se pudo cargar el resumen financiero. Revisa las fechas y la habilitación del módulo.':'Could not load financial summary. Check the dates and module setup.'}</p>:!summary?.length?<p>{es?'No hay movimientos registrados en este período.':'No recorded movements for this period.'}</p>:summary.map((s:any)=><section className="premium-card rounded-2xl p-5" key={s.currency}><h2 className="text-gold mb-4">{s.currency}</h2><div className="grid grid-cols-2 lg:grid-cols-5 gap-5">{[[es?'Cobros registrados':'Recorded collections',s.collected],[es?'Reembolsos':'Refunds',s.refunded],[es?'Gastos pagados':'Paid expenses',s.expenses],[es?'Pagos a técnicos':'Technician payments',s.payroll],[es?'Flujo neto registrado':'Recorded net cash flow',s.net]].map(([label,value])=><div key={String(label)}><p className="text-xs text-cool-gray">{label}</p><p className="text-xl font-semibold mt-2">{new Intl.NumberFormat(locale,{style:'currency',currency:s.currency}).format(Number(value))}</p></div>)}</div></section>)}
 <p className="text-xs text-cool-gray">{es?'Basado en movimientos registrados, separados por moneda. El flujo neto no representa utilidad contable. Las facturas sin cobrar y las jornadas sin pagar se consultan por separado.':'Based on recorded movements, separated by currency. Net cash flow is not accounting profit. Unpaid invoices and unpaid workdays are reviewed separately.'}</p>
 <details className="premium-card p-5 rounded-2xl"><summary className="font-semibold cursor-pointer text-gold">{es?'+ Registrar gasto pagado':'+ Record paid expense'}</summary><ActionForm action={recordExpense} resetOnSuccess className="grid sm:grid-cols-2 gap-4 mt-4"><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><Field label={es?'Descripción':'Description'}><input required name="description" className={inputClass}/></Field><Field label={es?'Importe':'Amount'}><input required type="number" name="amount" min="0.01" step="0.01" className={inputClass}/></Field><Field label={es?'Moneda':'Currency'}><select name="currency" className={inputClass}>{['USD','COP','DOP','EUR'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label={es?'Fecha de pago':'Payment date'}><input required type="date" name="paidOn" className={inputClass}/></Field><Field label={es?'Categoría':'Category'}><select name="category" className={inputClass}>{[['supplies',es?'Materiales':'Supplies'],['travel',es?'Transporte':'Travel'],['overhead',es?'Gastos generales':'Overhead'],['other',es?'Otros':'Other']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label={es?'Referencia':'Reference'}><input required name="reference" className={inputClass}/></Field><p className="text-xs text-cool-gray col-span-full">{es?'Registra los pagos a técnicos desde su ficha para evitar contarlos dos veces.':'Record technician payments from their profile to avoid counting them twice.'}</p><button className="command-action">{es?'Guardar gasto':'Save expense'}</button></ActionForm></details>
 <section className="premium-card p-5 rounded-2xl"><h2 className="text-lg mb-4">{es?'Gastos del período':'Period expenses'}</h2>{expenseError?<p role="alert">{es?'No se pudo cargar el historial.':'Could not load history.'}</p>:(expenses??[]).map(e=><div className="flex justify-between gap-4 py-3 border-b border-white/10" key={e.id}><span>{e.description}<small className="block text-cool-gray">{e.paid_on} · {e.reference}</small></span><span>{new Intl.NumberFormat(locale,{style:'currency',currency:e.currency}).format(e.amount)}</span></div>)}</section>
 </div>;
}
