import {createClient} from '@/lib/supabase/server';
import {getLocale} from '@/lib/i18n/server';
import {ActionForm} from '@/components/ui/ActionForm';
import {manageMonthlyCharge} from '@/lib/launch/monthly-fee';
export async function MonthlyCharges({organizationId,canManage=false}:{organizationId:string;canManage?:boolean}){
 const locale=await getLocale();const es=locale==='es';const db=await createClient();const {data:charges,error}=await db.from('platform_manual_charges').select('*').eq('organization_id',organizationId).order('billed_month',{ascending:false}).limit(24);
 return <details className="premium-card rounded-2xl p-5"><summary className="cursor-pointer font-semibold">{es?'Mensualidades y pagos':'Monthly charges & payments'}</summary>{error?<p className="mt-3 text-amber-200">{es?'Pendiente de habilitación.':'Setup pending.'}</p>:<div className="mt-4 space-y-4">{canManage&&<ActionForm action={manageMonthlyCharge} className="flex flex-wrap gap-3 items-end"><input type="hidden" name="organizationId" value={organizationId}/><label>{es?'Mes':'Month'}<input required type="month" name="month" className="block bg-white/5 border border-white/15 rounded-lg p-3"/></label><label>{es?'Vencimiento':'Due date'}<input required type="date" name="dueOn" className="block bg-white/5 border border-white/15 rounded-lg p-3"/></label><button className="command-action">{es?'Registrar mensualidad':'Record monthly charge'}</button></ActionForm>}
 {(charges??[]).map(c=><div key={c.id} className="border-t border-white/10 pt-4"><div className="flex justify-between gap-3"><p>{c.billed_month.slice(0,7)} · {new Intl.NumberFormat(locale,{style:'currency',currency:c.currency}).format(c.amount)}</p><p className={c.paid_at?'text-emerald-300':'text-amber-200'}>{c.paid_at?(es?'Pagado':'Paid'):(es?'Pendiente':'Pending')}</p></div><p className="text-sm text-cool-gray">{es?'Vence':'Due'} {c.due_on} {c.payment_reference?`· ${c.payment_reference}`:''}</p>{canManage&&!c.paid_at&&<details className="mt-2"><summary className="text-gold cursor-pointer">{es?'Registrar pago recibido':'Record received payment'}</summary><ActionForm action={manageMonthlyCharge} className="flex flex-wrap gap-3"><input type="hidden" name="organizationId" value={organizationId}/><input type="hidden" name="chargeId" value={c.id}/><input name="reference" required minLength={3} placeholder={es?'Referencia del pago':'Payment reference'} className="rounded-xl p-3 bg-white/5 border border-white/15"/><button className="command-action">{es?'Confirmar pago total':'Confirm full payment'}</button></ActionForm></details>}</div>)}{!charges?.length&&<p className="text-cool-gray">{es?'Sin mensualidades registradas.':'No monthly charges recorded.'}</p>}</div>}</details>;
}
