import { redirect } from 'next/navigation';
import { getSessionContext } from '@/lib/auth/session';
import { getActiveOrganizationId } from '@/lib/auth/active-org';
import { safeInternalPath } from '@/lib/auth/site-url';
import { roleHome } from '@/lib/auth/role-home';
import { createClient } from '@/lib/supabase/server';
import { getLocale } from '@/lib/i18n/server';
import { commandCopy } from '@/lib/i18n/command-copy';
import { ProfileSetup } from '@/components/auth/ProfileSetup';
import { LanguageSwitch } from '@/components/ui/LanguageSwitch';
import { AuthExperienceShell } from '@/components/auth/AuthExperienceShell';

export default async function WelcomePage({
  searchParams,
}: {
  searchParams: Promise<{ organization?: string; next?: string }>;
}) {
  const session = await getSessionContext();
  const params = await searchParams;

  if (session.passwordSetupRequired && !session.passwordSetupComplete) {
    const after = params.organization
      ? `/welcome?organization=${encodeURIComponent(params.organization)}${params.next ? `&next=${encodeURIComponent(params.next)}` : ''}`
      : '/welcome';
    redirect(`/reset-password?welcome=1&next=${encodeURIComponent(after)}`);
  }

  const org =
    params.organization && session.memberships.some((m) => m.organization_id === params.organization)
      ? params.organization
      : await getActiveOrganizationId(session.memberships);
  const role = session.memberships.find((m) => m.organization_id === org)?.role;

  const db = await createClient();
  const { data: profile } = await db
    .from('profiles')
    .select('full_name,phone,avatar_url')
    .eq('id', session.userId)
    .single();

  const locale = await getLocale();
  const t = commandCopy[locale];
  const roleDestination = roleHome(role, session.isKccAdmin);

  const requested = safeInternalPath(params.next, roleDestination);
  // First-run routing is role-authoritative. The query param can preserve the
  // expected destination generated by the invitation flow, but never move a
  // user into a different role's home.
  const destination = requested === roleDestination ? requested : roleDestination;

  return (
    <AuthExperienceShell
      eyebrow={locale === 'es' ? 'Último paso' : 'Final setup'}
      title={locale === 'es' ? 'Hazlo tuyo' : 'Make it yours'}
      description={locale === 'es'
        ? 'Tu acceso ya está protegido. Completa tu perfil y Marine Cloud abrirá automáticamente el panel correcto para tu función.'
        : 'Your access is secured. Complete your profile and Marine Cloud will automatically open the workspace for your role.'}
      steps={[
        { label: locale === 'es' ? 'Invitación' : 'Invitation', state: 'done' },
        { label: locale === 'es' ? 'Contraseña' : 'Password', state: 'done' },
        { label: locale === 'es' ? 'Perfil' : 'Profile', state: 'active' },
      ]}
    >
      <div className="flex justify-end -mt-2 mb-4">
        <LanguageSwitch current={locale} variant="onDark" />
      </div>
      <ProfileSetup
        organizationId={org}
        name={profile?.full_name || ''}
        phone={profile?.phone || ''}
        avatar={profile?.avatar_url || null}
        destination={destination}
      />
      <p className="mt-5 text-center text-[10px] text-cool-gray">{t.setupDetail}</p>
    </AuthExperienceShell>
  );
}
